### ISSUE TITLE
remove_repetition 

### ISSUE THREAD

**Issue by mmichelli** [bminixhofer/wtpsplit#111]
When I run remove_repetition(4)
I sometimes get an error: 

 remove_repetition
    self.remove_word(all_words[j], False, verbose=False)
    
  line 1545, in remove_word
    raise ValueError('word not in result')
ValueError: word not in result

**Comment by bminixhofer** [comment]
What is `remove_repetition`? This does not look related to the `wtpsplit` code to me? Please reopen if I am missing something.

**Comment by mmichelli** [comment]
So sorry, I posted the issue to the wrong repo.
