### ISSUE TITLE
Huggingface AutoModelForTokenClassification bug

### ISSUE THREAD

**Issue by asusdisciple** [bminixhofer/wtpsplit#112]
If you load "canine s12l no adapters" with the `AutoModelForTokenClassification` class and `from_pretrained` method with hugginface you get an `KeyError: "la-canine"`.
I looked for a key in `configuration_auto.py` and only found `"canine"`. Should be a quick fix.

**Comment by bminixhofer** [comment]
Hi!

`la-canine` is a custom model class registered by wtpsplit.

Try importing `wtpsplit` first (like here: https://github.com/bminixhofer/wtpsplit#advanced-usage), that should solve it.

**Comment by ohyooo** [comment]
i know..

import wtpsplit.models

**Comment by bminixhofer** [comment]
Good catch. Updated in the readme and closing this!
