### ISSUE TITLE
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by v-yunbin** [bminixhofer/wtpsplit#56]
i run it on centos7 and python3.8.3，and i just want to run it on cpu not gpu. I met follows error：
```
>>> import nnsplit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/zyb/miniconda3/lib/python3.8/site-packages/nnsplit.cpython-38-x86_64-linux-gnu.so)
```

**Comment by anigmo97** [comment]
I'm also having the same issue.
It's not possible to run this on Amazon Linux or AWS services in general.

**Comment by bminixhofer** [comment]
Hi! Sorry for being so quiet on this library. I have been working on a major revamp, expanding support to 85 languages, switching to a new training objective without labelled data, and switching the backbone to a BERT-style model.

It now does not have a Rust build in the background anymore so this should be solved! Please let me know if this persists.
