### ISSUE TITLE
Apple Silicon / Arm support

### ISSUE THREAD

**Issue by yenson-lau** [bminixhofer/wtpsplit#88]
What will it take to get support on Apple Silicon / ARM? I'm happy to help out with testing if that can be useful.

**Comment by bminixhofer** [comment]
Hi! Sorry for being so quiet on this library. I have been working on a major revamp, expanding support to 85 languages, switching to a new training objective without labelled data, and switching the backbone to a BERT-style model. 

The new version (now called `wtpsplit`) supports Apple Silicon out of the box (tested on my M1 Mac).

**Comment by miraclebakelaser** [comment]
Apple Silicon support, foreign language support, _and_ paragraph segmentation.. you hit the nail on the head with this release. I'm excited to try it out, thank you!
