### ISSUE TITLE
[Bug] Pandas not listed in `install_requires`, resulting in import error

### ISSUE THREAD

**Issue by mosheduminer** [bminixhofer/wtpsplit#92]
When I tried to import `wtpsplit` to try it out, the program failed with an import error.

It appears that `wtpsplit` uses `pandas` (and imports it at the top level), but does not list it in [`setup.py`](https://github.com/bminixhofer/wtpsplit/blob/main/setup.py#L10), so it doesn't automatically get installed when `wtpsplit` is installed.

I can make a PR if you'd like (though I know it is a very small thing, lol).

**Comment by bminixhofer** [comment]
Good catch, and sorry for being so slow here. It's fixed in v1.2.0 ([link](https://github.com/bminixhofer/wtpsplit/releases/tag/1.2.0)).
